import Head from 'next/head'
import Image from 'next/image'
import Navbar from "../components/Navbar";
import Main from "../components/Main";
import Committees from "../components/Committees";
import Footer from "../components/Footer";
import Comingsoon from '../components/comingsoon'

const prefix = process.env.NEXT_PUBLIC_BASE_PATH;

export default function Home() {
  return (
    <div>
      <Head>
        <title>DelTech MUN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={prefix + "/favicon.ico"} />
      </Head>

      <Navbar/>
      <Main/>
      <Comingsoon></Comingsoon>
      {/* <Committees/> */}
      <Footer />
    </div>
  )
}
